name: Deploy RAG backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: terraform
    environment: production
    steps:
      - name : Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push docker image
      #   id: build-and-push-image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags : ${{ secrets.ECR_REPOSITORY }}:latest
      - name: Deploy to EC2 via SSM
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=compdi-instance" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)

          if [ "$INSTANCE_ID" = "None" ] || [ -z "$INSTANCE_ID" ]; then
            echo "ERROR: No EC2 instance found"
            exit 1
          fi

          aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy new backend image" \
          --parameters '{"commands": [
            "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 639135895801.dkr.ecr.us-east-2.amazonaws.com",
            "docker pull 639135895801.dkr.ecr.us-east-2.amazonaws.com/uvg/comp_digital:latest",
            "docker stop comp_digital || true",
            "docker rm comp_digital || true",
            "docker run -d --name comp_digital -p 80:80 639135895801.dkr.ecr.us-east-2.amazonaws.com/uvg/comp_digital:latest"
          ]}' \
          --region us-east-2 \
          --output text
      - name: Check SSM command output
        run: |
          COMMAND_ID=$(aws ssm list-commands \
            --query "Commands[0].CommandId" \
            --output text)

          echo "COMMAND_ID: $COMMAND_ID"

          aws ssm list-command-invocations \
            --command-id "$COMMAND_ID" \
            --details \
            --output text


