name: Deploy RAG backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: terraform
    environment: production
    steps:
      - name : Checkout repo
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push docker image
        id: build-and-push-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags : ${{ secrets.ECR_REPOSITORY }}:latest
