name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Escribe DESTROY para confirmar la eliminación de la infraestructura"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_database_username: ${{ secrets.DATABASE_USERNAME }}
      TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/comp-digital-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.S3_TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TERRAFORM_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Safety check
        if: ${{ github.event.inputs.confirm != 'DESTROY' }}
        run: |
          echo "❌ Confirmación inválida. Escribe DESTROY para continuar."
          exit 1

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
